name: Run Tests
permissions:
  contents: write
on:
  push:
    branches-ignore:
      - main
  workflow_call:
jobs:
  tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 26
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit-polyfills
      - name: Git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --optimize-autoloader
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Roll install - Use HTTPS for GitHub
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - name: Install dependencies
        run: bun install
      - name: Install dev plugins (ACF, Elementor, Beaver Builder, WP Fusion)
        run: bun run install:dev
      - name: Install playwright
        run: bun run e2e:install
      - name: PHPUnit - Run tests for PHP 7.4
        run: bun run env:test:7.4
      - name: End to end - PHP 7.4
        run: bun run e2e
      - name: PHPUnit - Run tests for PHP 8.2
        run: bun run env:test:8.2
      - name: End to end - PHP 8.2
        run: bun run e2e
      - name: PHPUnit - Run tests for PHP 8.4
        run: bun run env:test:8.4
      - name: End to end - PHP 8.4
        run: bun run e2e
